"""`fsc init` and friends via typer's CliRunner.

`init` is the one command with real logic (prompt/flag/default resolution,
validation, warn-only sanity probes); everything else here is smoke.
"""

from __future__ import annotations

from pathlib import Path

import httpx
import yaml
from typer.testing import CliRunner

from marcellus import __version__
from marcellus.cli import app
from marcellus.config import Settings

runner = CliRunner()


def _init(tmp_path: Path, *extra: str) -> tuple[int, str]:
    out = tmp_path / "sidecar.yml"
    result = runner.invoke(
        app, ["init", "--output", str(out), "--non-interactive", *extra]
    )
    return result.exit_code, result.output


def test_init_writes_valid_config(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr(httpx, "get", _raise_connect)
    code, output = _init(tmp_path)
    assert code == 0
    assert "Wrote" in output
    written = (tmp_path / "sidecar.yml").read_text()
    assert written.startswith("# Generated by `fsc init`")
    # The generated document must round-trip through the real settings model.
    Settings.model_validate(yaml.safe_load(written))


def test_init_flags_override_defaults(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr(httpx, "get", _raise_connect)
    code, _ = _init(
        tmp_path,
        "--frigate-url", "http://nvr.example:5000",
        "--bind-port", "6001",
    )
    assert code == 0
    cfg = yaml.safe_load((tmp_path / "sidecar.yml").read_text())
    assert cfg["frigate"]["base_url"] == "http://nvr.example:5000"
    assert cfg["sidecar"]["bind_port"] == 6001


def test_init_refuses_existing_file_without_force(tmp_path: Path) -> None:
    out = tmp_path / "sidecar.yml"
    out.write_text("keep me\n")
    result = runner.invoke(app, ["init", "--output", str(out), "--non-interactive"])
    assert result.exit_code == 1
    assert "use --force" in result.output
    assert out.read_text() == "keep me\n"


def test_init_force_overwrites(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr(httpx, "get", _raise_connect)
    out = tmp_path / "sidecar.yml"
    out.write_text("old\n")
    code, _ = _init(tmp_path, "--force")
    assert code == 0
    assert out.read_text().startswith("# Generated by `fsc init`")


def test_init_version_probe_failure_is_warn_only(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr(httpx, "get", _raise_connect)
    code, output = _init(tmp_path)
    assert code == 0
    assert "Could not reach Frigate" in output


def test_init_version_probe_success_reported(tmp_path: Path, monkeypatch) -> None:
    def fake_get(url: str, timeout: float) -> httpx.Response:
        return httpx.Response(200, text="0.17.2", request=httpx.Request("GET", url))

    monkeypatch.setattr(httpx, "get", fake_get)
    code, output = _init(tmp_path)
    assert code == 0
    assert "Frigate reachable" in output


def test_init_missing_frigate_paths_warn_only(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr(httpx, "get", _raise_connect)
    code, output = _init(
        tmp_path,
        "--frigate-db", str(tmp_path / "missing" / "frigate.db"),
        "--recordings-path", str(tmp_path / "missing" / "recordings"),
    )
    assert code == 0
    assert "Frigate DB not found" in output
    assert "does not exist" in output


def test_init_existing_frigate_paths_reported(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setattr(httpx, "get", _raise_connect)
    db = tmp_path / "frigate.db"
    db.write_bytes(b"")
    rec = tmp_path / "recordings"
    rec.mkdir()
    code, output = _init(
        tmp_path, "--frigate-db", str(db), "--recordings-path", str(rec)
    )
    assert code == 0
    assert "Frigate DB found" in output
    assert "Recordings path exists" in output


def test_version_prints_package_version() -> None:
    result = runner.invoke(app, ["version"])
    assert result.exit_code == 0
    assert __version__ in result.output


def _raise_connect(url: str, timeout: float) -> httpx.Response:
    raise httpx.ConnectError("test: no frigate here")


def _write_config(tmp_path: Path) -> Path:
    frigate_db = tmp_path / "frigate.db"
    frigate_db.write_bytes(b"")
    cfg = tmp_path / "sidecar.yml"
    cfg.write_text(
        yaml.safe_dump(
            {
                "frigate": {"db_path": str(frigate_db)},
                "sidecar": {"db_path": str(tmp_path / "marcellus.db")},
            }
        )
    )
    return cfg


def test_backup_and_restore_round_trip(tmp_path: Path, monkeypatch) -> None:
    cfg = _write_config(tmp_path)
    monkeypatch.setenv("MARCELLUS_CONFIG", str(cfg))

    from marcellus import db

    sidecar_db = tmp_path / "marcellus.db"
    db.open_sidecar(sidecar_db).close()

    dest = tmp_path / "backup"
    result = runner.invoke(app, ["backup", str(dest)])
    assert result.exit_code == 0, result.output
    assert "Wrote backup" in result.output
    assert (dest / "manifest.json").exists()

    result = runner.invoke(app, ["restore", str(dest), "--force"])
    assert result.exit_code == 0, result.output
    assert "Restored" in result.output


def test_restore_without_force_exits_1(tmp_path: Path, monkeypatch) -> None:
    cfg = _write_config(tmp_path)
    monkeypatch.setenv("MARCELLUS_CONFIG", str(cfg))

    from marcellus import db

    sidecar_db = tmp_path / "marcellus.db"
    db.open_sidecar(sidecar_db).close()

    dest = tmp_path / "backup"
    runner.invoke(app, ["backup", str(dest)])
    result = runner.invoke(app, ["restore", str(dest)])
    assert result.exit_code == 1
    assert "stop marcellus" in result.output


def test_backup_missing_db_exits_1(tmp_path: Path, monkeypatch) -> None:
    cfg = _write_config(tmp_path)
    monkeypatch.setenv("MARCELLUS_CONFIG", str(cfg))

    result = runner.invoke(app, ["backup", str(tmp_path / "backup")])
    assert result.exit_code == 1
    assert "not found" in result.output
